server:
  port: 8060

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, integrationsHealth
      path-mapping:
        integrationsHealth: /integrations/health
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}


producer:
  exchange:
    name: consumer-exchange
  dl-exchange:
    name: consumer-dl-exchange
  queue:
    name: consumer_queue
    routing-keys: consumer_routing_key
  dead-letter-queue:
    name: consumer_deadletter_queue
    routing-key: CONSUMER.DEADLETTER
  retry-queue:
    name: consumer_queue
    routing-key: CONSUMER.RETRY
  parking-lot-queue:
    name: consumer_parkinglot_queue
    routing-key: CONSUMER.PARK
  message-retry-count: 4
  message-ttl: 6000


